---
version: 2.0
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: d9e81ef3f8dadc52e2285c8a470999bc535b028e814a8463936c6caaf6bcdb41
docker:
  - image: circleci/openjdk:11-jdk
steps:
  - checkout
  - run:
      name: Build and Test
      command: |
        mvn clean install
plugins:
  jacoco:
    enabled: true
